
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#C00100',
        'secondary': '#006E21',
        'tertiary': '#705C2E',
        'error': '#BA1A1A',
        'primary-container': '#FFDAD4',
        'on-primary-container': '#410000',
        'secondary-container': '#7DFD86',
        'on-secondary-container': '#002105',
        'tertiary-container': '#FBDFA6',
        'on-tertiary-container': '#251A00',
        'error-container': '#FFDAD6',
        'on-error-container': '#410002',
        'primary-fixed': '#FFDAD4',
        'primary-fixed-dim': '#FFB4A8',
        'on-primary-fixed': '#930100',
        'secondary-fixed': '#7DFD86',
        'secondary-fixed-dim': '#60E06D',
        'on-secondary-fixed': '#005317',
        'tertiary-fixed': '#FBDFA6',
        'tertiary-fixed-dim': '#DEC48C',
        'on-tertiary-fixed': '#564419',
        'surface-dim': '#E4D7D5',
        'surface': '#FFF8F6',
        'surface-bright': '#FFF8F6',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#FEF1EE',
        'surface-container': '#F8EBE9',
        'surface-container-high': '#F3E5E3',
        'surface-container-highest': '#EDE0DD',
        'on-surface': '#201A19',
        'on-surface-variant': '#534341',
        'outline': '#857370',
        'outline-variant': '#D8C2BE',
        'inverse-surface': '#362F2E',
        'inverse-on-surface': '#FBEEEC',
        'inverse-primary': '#FFB4A8',
        'scrim': '#000000',
        'light': '#FFFBFF',
      },
      fontSize: {
        'body-small': '12px',
        'body-medium': '14px',
        'body-large': '16px',
        'label-small': '11px',
        'label-medium': '12px',
        'label-large': '14px',
        'title-small': '14px',
        'title-medium': '16px',
        'title-large': '22px',
        'headline-small': '24px',
        'headline-medium': '28px',
        'headline-large': '32px',
        'display-small': '36px',
        'display-medium': '45px',
        'display-large': '57px',
      },
      spacing: {
        '8': '8px',
        '16': '16px',
        '40': '40px',
        '42': '42px',
        '20': '20px'
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms')
  ],
}

